name: Matrix Demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [12, 14, 16]
                os: [ubuntu-latest, windows-latest]
        # We can set the runner dynamiclly, by using the matrix context object
        runs-on: ${{matrix.os}}
        steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}}
        - name: Install dependencies
          run: npm ci
        - name: Build Project
          run: npm run build
        #   Run the same job but using different version at the same time