name: Matrix Demo

# Useful if you have a testing process that should run on different operating systems, or you need to test the code against differebtnt version of noded
on: push
jobs:
    build:
        # We can use continue on error to make sure subsqent jobs continue if other jobs fail
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 16]
                # We can set the runner dynamiclly, by using the matrix context object
                os: [ubuntu-latest, windows-latest]
                # Standalone combinations
                # Resevered red key: KV combinations to be added to work flow
                # Where we specifically want node 18 and ubuntu-latest in workflow
                include:
                    - node-version: 18
                      os: ubuntu-latest
                # This combination will be 'excluded' from the workflow
                exclude: 
                    - node-version: 12
                      os: windows-latest
        runs-on: ${{matrix.os}}
        steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}}
        - name: Install dependencies
          run: npm ci
        - name: Build Project
          run: npm run build
        #   Run the same job but using different version at the same time