name: Reusable Workflows

on:
  workflow_call:  # Corrected event name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Corrected runner label
    steps:
      - name: output information
        run: echo "Deploying & Uploading.."
