name: Resuable Workflows
# To make a workflow resuable it must be 'callable'
on: workflow-call
jobs:
    deploy:
        runs-on: unbuntu-latest
        steps:
            - name: output information
            run: echo "Deploying & Uploading"
