name: Test git hub extentions 

on: 
    push: 
        branches: ["main"] 

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run: | 
                "echo hello world"
    